spring:
  profiles: 
    active: h2
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  output:
    ansi:
      enabled: always  # 콘솔 창에 출력되는 로깅 메세지를 색으로 구분해서 출력 
  jmx:
    default-domain: egovTest
  h2:
    console:
      enabled: true
      path: /db-console
  whois:
    key:   #whois에서 제공 하는 API를 사용하기 위해 발급받은 key를 등록한다.
    url: http://whois.kisa.or.kr/openapi/ipascc.jsp
server:
  port: 9087
  task:
    fixedDelay: 1000
    name: mariaTask

---

logging:
  file: /home/vagrant/memberMng/log/egovGrpMng.log
#    path: /home/vagrant/memberMng/log/egovGrpMng.log  # 로그 메세지가 저장되는 로그 디렉터리
#    path: C:\work\log\  # 로그 메세지가 저장되는 로그 디렉터리55555566666666fff55555
#    name: egovGrpMng.log
  size: max-10MB
  level:
    egovframework: DEBUG

---

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true

---

spring:
  profiles: h2 
  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: SA

---

spring:
  profiles: maria 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.33.20:3306/EGOVCLDDEV #local Vm
#    url: jdbc:mariadb://10.182.164.67:3306/EGOVCLDDEV  #개발
#    url: jdbc:mariadb://220.73.22.204:9606/EGOVCLDDEV #개발(bastion) 
    username: egovclddev
    password: Helloegov1!
  jpa:
    hibernate:
      ddl-auto: update
      ddl: true
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
---
security:
  user: admin
  password: cb!234